"""fix user id

Revision ID: c0327954f524
Revises: cba1211bbf5f
Create Date: 2025-11-15 20:54:02.410503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0327954f524'
down_revision: Union[str, Sequence[str], None] = 'cba1211bbf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    op.drop_constraint('clients_user_id_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('guides_user_id_fkey', 'guides', type_='foreignkey')
    op.drop_constraint('moderators_user_id_fkey', 'moderators', type_='foreignkey')

    op.drop_constraint('users_pkey', 'users', type_='primary')

    op.drop_column('users', 'id')

    op.add_column(
        'users',
        sa.Column(
            'id',
            sa.Integer(),
            sa.Identity(always=False),   # GENERATED BY DEFAULT AS IDENTITY
            primary_key=True,
            nullable=False,
        ),
    )

    op.create_primary_key('users_pkey', 'users', ['id'])

    op.create_foreign_key(
        'clients_user_id_fkey',
        'clients', 'users',
        ['user_id'], ['id'],
    )
    op.create_foreign_key(
        'guides_user_id_fkey',
        'guides', 'users',
        ['user_id'], ['id'],
    )
    op.create_foreign_key(
        'moderators_user_id_fkey',
        'moderators', 'users',
        ['user_id'], ['id'],
    )


def downgrade():
    op.drop_constraint('clients_user_id_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('guides_user_id_fkey', 'guides', type_='foreignkey')
    op.drop_constraint('moderators_user_id_fkey', 'moderators', type_='foreignkey')

    op.drop_constraint('users_pkey', 'users', type_='primary')

    op.drop_column('users', 'id')

