"""user update for auth

Revision ID: cba1211bbf5f
Revises: 082e78445e96
Create Date: 2025-11-14 20:00:28.253951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba1211bbf5f'
down_revision: Union[str, Sequence[str], None] = '082e78445e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('clients_user_id_fkey'), 'clients', type_='foreignkey')
    op.drop_constraint(op.f('guides_user_id_fkey'), 'guides', type_='foreignkey')
    op.drop_constraint(op.f('moderators_user_id_fkey'), 'moderators', type_='foreignkey')


    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('users_pkey', 'users', type_='primary')

    op.create_primary_key('users_pkey', 'users', ['id'])

    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'user_id')

    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'guides', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'moderators', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderators', type_='foreignkey')
    op.drop_constraint(None, 'guides', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')



    op.add_column('users', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'id')
    op.create_foreign_key(op.f('moderators_user_id_fkey'), 'moderators', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('guides_user_id_fkey'), 'guides', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('clients_user_id_fkey'), 'clients', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
